/* 博士雷达 · 每日研究日报。数据由 daily_dashboard.py 生成到 data/daily_data.js。 */
(function () {
  'use strict';
  var DEMO = {isDemo:true,date:'2026-08-18',reportStatus:'演示占位',scanCount:100,dataStatus:'占位 · 未接真实',asof:'占位',summary:{complete:'—',scanCount:100,rankingFocus:'—',divergence:'—',skdjObserve:'—',statusCount:'—',exceptions:'—'},exceptions:[],tools:{},rows:[
    {ticker:'AAPL',name:'Apple',resonance:'共振',rankings:'②背离观察',divergence:'底背离',skdj:'超跌',statuschain:'BASE'},
    {ticker:'NVDA',name:'NVIDIA',resonance:'共振',rankings:'①已确认',divergence:'无结果',skdj:'无结果',statuschain:'CONFIRM'},
    {ticker:'MSFT',name:'Microsoft',resonance:'单边',rankings:'③强趋势',divergence:'TD9≥9',skdj:'回调',statuschain:'OBSERVE'},
    {ticker:'AMZN',name:'Amazon',resonance:'无结果',rankings:'无结果',divergence:'无结果',skdj:'无结果',statuschain:'无结果'},
    {ticker:'TSLA',name:'Tesla',resonance:'数据不足',rankings:'⑤噪音',divergence:'顶背离',skdj:'超买',statuschain:'INVALID'},
    {ticker:'META',name:'Meta',resonance:'共振',rankings:'④潜力',divergence:'无结果',skdj:'低位上穿',statuschain:'TRIGGER'},
    {ticker:'GOOGL',name:'Alphabet',resonance:'单边',rankings:'无结果',divergence:'无结果',skdj:'普通区',statuschain:'无结果'},
    {ticker:'AMD',name:'AMD',resonance:'数据不足',rankings:'②背离观察',divergence:'TD9≥9',skdj:'超跌',statuschain:'OBSERVE'}
  ],history:[]};
  var DATA=window.DAILY_DATA&&window.DAILY_DATA.version?window.DAILY_DATA:DEMO;
  var cmpRows=DATA.rows||[], cmpState={sortKey:'ticker',sortDir:'asc',filter:''};
  var STATUS_LABEL={OBSERVE:'观察中',BASE:'底部形成',TRIGGER:'条件触发',CONFIRM:'已确认',INVALID:'已失效',EXPIRED:'已过期',NOISE:'噪音'};
  var STATUS_CLASS={OBSERVE:'pill-stage-observe',BASE:'pill-stage-base',TRIGGER:'pill-stage-trigger',CONFIRM:'pill-stage-confirm',INVALID:'pill-stage-invalid',EXPIRED:'pill-stage-expired',NOISE:'pill-stage-noise'};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function setText(sel,v){var n=document.querySelector(sel);if(n)n.textContent=v==null?'—':String(v);}
  function statusText(v){var k=String(v||'');return STATUS_LABEL[k]?STATUS_LABEL[k]+' · '+k:k;}
  function pillClass(col,v){var s=String(v||''),k=s.split(' · ')[0];if(col==='statuschain'&&STATUS_CLASS[k])return STATUS_CLASS[k];if(col==='resonance'){if(/多头|偏多/.test(s))return'pill-positive';if(/空头|偏空/.test(s))return'pill-negative';return'pill-neutral';}if(col==='rankings'){if(/突破|多头|确认|高潜力/.test(s))return'pill-positive';if(/空头|风险噪音/.test(s))return'pill-negative';return'pill-neutral';}if(col==='divergence'){if(/底背离/.test(s))return'pill-positive';if(/顶背离|TD9Sell/.test(s))return'pill-negative';return'pill-neutral';}if(col==='skdj'){if(/超跌|低位上穿/.test(s))return'pill-positive';if(/超买|高位下穿/.test(s))return'pill-negative';return'pill-neutral';}return'pill-neutral';}
  function cell(v,col){if(!v||v==='无结果')return'<span class="pill-empty">无结果</span>';var text=col==='statuschain'?statusText(v):String(v);return'<span class="pill '+pillClass(col,v)+'">'+esc(text)+'</span>';}
  function setSummary(){var s=DATA.summary||{}, vals={complete:s.complete||DATA.reportStatus||'—',scanCount:(s.scanCount==null?DATA.scanCount:s.scanCount)+'只',rankingFocus:s.rankingFocus==null?'—':s.rankingFocus+'只',divergence:s.divergence==null?'—':s.divergence+'只',skdjObserve:s.skdjObserve==null?'—':s.skdjObserve+'只',statusCount:s.statusCount==null?'—':s.statusCount+'条',exceptions:s.exceptions?s.exceptions+'项':'无异常'};Object.keys(vals).forEach(function(k){var n=document.querySelector('[data-summary="'+k+'"]');if(n)n.innerHTML=esc(vals[k]);var note=document.querySelector('[data-summary-note="'+k+'"]');if(note)note.textContent=DATA.isDemo?'演示占位':(k==='exceptions'?((DATA.exceptions||[]).join('；')||'未发现异常'):'来自正式日报数据');});setText('#sbDate',DATA.date||'—');setText('#sbScan',(DATA.scanCount||0)+' 只');setText('#sbAsof',DATA.asof||'未提供');setText('#overviewLead',DATA.isDemo?'把五个工具的结果汇总成一组查看顺序。下方为演示占位数据。':'把五个工具的结果汇总成一组查看顺序。当前页面读取已生成的案例或本地日报，未新增行情请求。');var st=document.getElementById('sbStatus'),dt=document.getElementById('sbData'),bn=document.getElementById('demoBanner');if(st){st.textContent=DATA.reportStatus||'—';st.className='sb-value tag '+(DATA.isDemo?'tag-demo':'tag-mute');}if(dt){dt.textContent=DATA.dataStatus||'—';dt.className='sb-value tag '+(DATA.isDemo?'tag-mute':'tag-demo');}if(bn){bn.hidden=!DATA.isDemo;if(!DATA.isDemo)bn.textContent='本页读取已生成的案例或本地日报；不新增 API 请求。状态链与候选规则提示仍以原始报告为准。';}setText('#cmpSub',DATA.isDemo?'把同一只股票在五个工具里的证据并排展示。下方为演示占位数据。':'把同一只股票在五个工具里的结果并排展示。空值显示为「无结果」，不把缺失报告当成无信号。');setText('#cmpFoot',DATA.isDemo?'占位说明：表格数据为演示用静态行。':'当前对比表按股票代码合并正式 CSV；“无结果”表示该工具没有纳入正式结果，不等于没有信号。');setText('#calNote',DATA.isDemo?'占位说明：日历日期与状态均为演示占位。':'点击有日报的日期，会切换到对应日期的数据文件；没有独立入口的历史日期只显示状态，不冒充完整日报。');}
  function renderTable(){var body=document.getElementById('cmpBody');if(!body)return;var list=cmpRows.slice(),q=cmpState.filter.toLowerCase();if(q)list=list.filter(function(r){return String(r.ticker).toLowerCase().indexOf(q)>-1||String(r.name||'').toLowerCase().indexOf(q)>-1;});var k=cmpState.sortKey;list.sort(function(a,b){var va=String(a[k]==null?'':a[k]),vb=String(b[k]==null?'':b[k]),ae=!va||va==='无结果',be=!vb||vb==='无结果';if(ae&&!be)return 1;if(!ae&&be)return-1;var x=va.localeCompare(vb,'zh');return cmpState.sortDir==='asc'?x:-x;});document.querySelectorAll('.cmp-table th.sortable').forEach(function(th){th.classList.remove('sorted-asc','sorted-desc');if(th.getAttribute('data-sort')===k)th.classList.add(cmpState.sortDir==='asc'?'sorted-asc':'sorted-desc');});setText('#cmpCount',(DATA.isDemo?'占位 ':'')+list.length+' 行');body.innerHTML=list.length?list.map(function(r){return'<tr><td class="td-ticker">'+esc(r.ticker)+'<span class="tk-name">'+esc(r.name||'')+'</span></td><td>'+cell(r.resonance,'resonance')+'</td><td>'+cell(r.rankings,'rankings')+'</td><td>'+cell(r.divergence,'divergence')+'</td><td>'+cell(r.skdj,'skdj')+'</td><td>'+cell(r.statuschain,'statuschain')+'</td><td class="td-view"><a href="#" data-ticker="'+esc(r.ticker)+'" onclick="return false;">查看 ↗</a></td></tr>';}).join(''):'<tr class="cmp-empty-row"><td colspan="7">无结果</td></tr>';}
  function initTable(){renderTable();var input=document.getElementById('cmpSearch');if(input)input.addEventListener('input',function(){cmpState.filter=input.value.trim();renderTable();});document.querySelectorAll('.cmp-table th.sortable').forEach(function(th){th.addEventListener('click',function(){var k=th.getAttribute('data-sort');if(cmpState.sortKey===k)cmpState.sortDir=cmpState.sortDir==='asc'?'desc':'asc';else{cmpState.sortKey=k;cmpState.sortDir='asc';}renderTable();});});}
  function bodyFor(k,t){if(!t||!t.complete)return'没有找到当天的正式报告。带 smoke、test、demo 或 synthetic 的文件没有纳入日报。';if(k==='resonance')return'正式报告包含 '+t.count+' 只股票。下面直接嵌入完整多周期报告。';if(k==='rankings')return'正式五榜日报包含 '+t.count+' 只股票。下面直接嵌入完整榜单报告。';if(k==='divergence')return'正式背离 / TD9 报告包含 '+t.count+' 个结果。下面直接嵌入完整报告。';if(k==='skdj')return'正式 SKDJ 报告包含 '+t.count+' 只股票；当前候选公式状态必须以“未验证”理解。下面直接嵌入完整报告。';return'状态链已读取本地 SQLite；下面嵌入状态链 HTML 回放页面。';}
  function resizeReportFrame(frame){try{var doc=frame.contentDocument||frame.contentWindow.document;var height=Math.max(doc.documentElement.scrollHeight,doc.body?doc.body.scrollHeight:0);if(height)frame.style.height=(height+24)+'px';}catch(e){frame.style.height='calc(100vh - 220px)';}}
  function initTools(){['resonance','rankings','divergence','skdj','statuschain'].forEach(function(k){var t=(DATA.tools||{})[k]||{},body=document.querySelector('[data-tool-body="'+k+'"]');setText('[data-tool-status="'+k+'"]',t.status||(DATA.isDemo?'演示占位':'未生成'));setText('[data-tool-source="'+k+'"]',t.source||'无正式报告');setText('[data-tool-asof="'+k+'"]',t.asof||'—');if(body){if(t.html&&t.complete&&!DATA.isDemo){body.innerHTML='<p class="detail-empty detail-summary">'+esc(bodyFor(k,t))+'</p><iframe class="report-frame" src="'+esc(t.html)+'" title="'+esc(k)+' 完整报告" loading="eager" scrolling="auto"></iframe>';var frame=body.querySelector('.report-frame');frame.addEventListener('load',function(){resizeReportFrame(frame);});}else{body.textContent=bodyFor(k,t);}}var a=document.querySelector('[data-report-link="'+k+'"]');if(a){if(t.html){a.href=t.html;a.target='_blank';a.removeAttribute('onclick');a.classList.remove('is-disabled');}else{a.textContent='暂无正式报告';a.classList.add('is-disabled');}}});}
  function initTabs(){var tabs=document.querySelectorAll('.nav-tabs .tab'),panels=document.querySelectorAll('.panel');function activate(target){tabs.forEach(function(t){t.classList.toggle('active',t.getAttribute('data-tab')===target);});panels.forEach(function(p){var yes=p.id==='panel-'+target;p.classList.toggle('is-active',yes);p.hidden=!yes;});window.scrollTo({top:0,behavior:'smooth'});}tabs.forEach(function(t){t.addEventListener('click',function(){activate(t.getAttribute('data-tab'));});});document.querySelectorAll('[data-back]').forEach(function(b){b.addEventListener('click',function(){activate(b.getAttribute('data-back'));});});}
  var calState={year:2026,month:7},calIndex={},LABEL={full:'完整',part:'部分',hist:'历史',miss:'缺失'};
  function pad(n){return n<10?'0'+n:''+n;}function fmt(y,m,d){return y+'-'+pad(m+1)+'-'+pad(d);}
  function renderCal(){var grid=document.getElementById('calGrid'),lab=document.getElementById('calMonthLabel');if(!grid||!lab)return;var y=calState.year,m=calState.month;lab.textContent=y+' 年 '+(m+1)+' 月';var lead=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),html='';for(var i=0;i<lead;i++)html+='<div class="cal-cell"></div>';for(var d=1;d<=days;d++){var ds=fmt(y,m,d),st=calIndex[ds],cl='cal-cell'+(st?' has lg-'+st:'')+(ds===DATA.date?' today':'');html+='<div class="'+cl+'"'+(st?' data-date="'+ds+'" data-status="'+st+'"':'')+'>'+d+(st?'<span class="cc-status">'+LABEL[st]+'</span>':'')+'</div>';}grid.innerHTML=html;grid.querySelectorAll('.cal-cell.has').forEach(function(c){c.addEventListener('click',function(){var ds=c.getAttribute('data-date');window.location.href='index.html?date='+ds;});});}
  function initCal(){(DATA.history||[]).forEach(function(x){calIndex[x.date]=x.status;});var o=document.getElementById('calOverlay'),open=document.getElementById('calOpenBtn'),close=document.getElementById('calCloseBtn');if(!o||!open||!close)return;function show(){o.hidden=false;renderCal();document.body.style.overflow='hidden';}function hide(){o.hidden=true;document.body.style.overflow='';}open.addEventListener('click',show);close.addEventListener('click',hide);o.addEventListener('click',function(e){if(e.target===o)hide();});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!o.hidden)hide();});document.getElementById('calPrev').addEventListener('click',function(){calState.month--;if(calState.month<0){calState.month=11;calState.year--;}renderCal();});document.getElementById('calNext').addEventListener('click',function(){calState.month++;if(calState.month>11){calState.month=0;calState.year++;}renderCal();});}
  function boot(){if(DATA.date&&/^\d{4}-\d{2}-\d{2}$/.test(DATA.date)){calState.year=Number(DATA.date.slice(0,4));calState.month=Number(DATA.date.slice(5,7))-1;}setSummary();initTable();initTools();initTabs();initCal();}
  var requested=new URLSearchParams(window.location.search).get('date');if(requested&&requested!==DATA.date&&/^\d{4}-\d{2}-\d{2}$/.test(requested)){var s=document.createElement('script');s.src='data/daily_data_'+requested.replace(/-/g,'')+'.js';s.onload=function(){DATA=window.DAILY_DATA||DATA;cmpRows=DATA.rows||[];boot();};s.onerror=function(){alert('历史日报数据文件不存在：'+requested+'。当前仍显示 '+DATA.date+' 的日报。');boot();};document.head.appendChild(s);}else boot();
})();
